core/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views
app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('report/', views.report, name='report'),
    path('about/', views.about, name='about'),
    path('filtering/<categories>', views.filtering, name='filtering'),
    path('contact/', views.contact, name='contact'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('request-refund/', views.RequestRefundView.as_view(), name='request-refund'),
    path('payment-confirmation/', csrf_exempt(views.paymentconf),
         name='payment-confirmation')
    #path('mpesa/', include('mpesa_api.core.urls', 'mpesa'))
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


# CATEGORY_CHOICES = (
#     ('S', 'Shirt'),
#     ('SW', 'Sport wear'),
#     ('OW', 'Outwear')
# )

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)
STATUS_CHOICEs = (
    ('T', 'PAID'),
    ('F', 'NOT PAID'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
CATEGORIES=(
            ('seat','seat'),
            ('tents', 'tents'),
            ('catering', 'catering'),
            ('Toilets', 'toilets'),
)

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(default=0)
    # category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    categories = models.CharField(choices=CATEGORIES, max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    quantity = models.IntegerField(default=10)

    def reduceqty(self):
        quantity = self.quantity - 1
        self.save()

    def __str__(self):
        return self.quantity

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    shipping_date = models.DateTimeField(default='2019-2-22')
    ordered_date = models.DateTimeField(default='2019-1-10')

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'mpesapayment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    mpesa_transaction_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)


class mpesapayment(models.Model):
    MerchantRequestID = models.CharField(max_length=50)
    Amount = models.CharField(max_length=50, null=True)
    MpesaReceiptNumber = models.CharField(max_length=50, null=True)
    PhoneNumber = models.CharField(max_length=50, null=True)
    Balance = models.CharField(max_length=50, null=True)
    TransactionDate = models.CharField(max_length=50, null=True)
    ResultCode = models.IntegerField()
    ResultDesc = models.CharField(max_length=50)
    CheckoutRequestID = models.CharField(max_length=50)
    # status = models.CharField(choices=STATUS_CHOICEs, Null=False, max_length=1)

    def __str__(self):
        return self.MerchantRequestID
    #
    # class ContactMessages(models.Model):
    #     name = models.CharField(max_length=150)
    #     email = models.EmailField(max_length=100)
    #     phone = models.IntegerField()
    #     message = models.CharField(max_length=250)
    #     timestamp = models.DateTimeField(auto_now_add=True)

static_in_env/templates/filtering.html
{% extends "base.html" %}

{% block content %}
    <style>
   #search:link {
  color: red;
}

/* visited link */
#search:visited {
  color: red;
}

/* mouse over link */
#search:hover {
  color: hotpink;
}

/* selected link */
#search:active {
  color: blue;
}
    </style>
<main>
  <div class="container">


    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
                   <a href="{% url 'core:home' %}" class="btn btn-success" style="margin-bottom: 5px">Home

              <span class="sr-only">(current)</span>
            </a>

          </li>
               <li class="nav-item active">
                   <a href="http://127.0.0.1:8000/filtering/tents" class="btn btn-success" style="margin-bottom: 5px">Tents

              <span class="sr-only">(current)</span>
            </a>

          </li>

               <li class="nav-item active">
                   <a href="http://127.0.0.1:8000/filtering/seat" class="btn btn-success" style="margin-bottom: 5px">Seats

              <span class="sr-only">(current)</span>
            </a>

          </li>
            <li class="nav-item active">
                   <a href="http://127.0.0.1:8000/filtering/Toilets" class="btn btn-success" style="margin-bottom: 5px">Toilets

              <span class="sr-only">(current)</span>
            </a>

          </li>
                 <li class="nav-item active">
                   <a href="http://127.0.0.1:8000/filtering/catering" class="btn btn-success" style="margin-bottom: 5px">Catering

              <span class="sr-only">(current)</span>
            </a>

          </li>

{##}
{#            <form action="filtering.html" method="get">#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" name="tent" href="{% url 'core:filtering' %}">Tents</a>#}
{#              <a href="?title=True" class="btn btn-{% if 'title' in request.GET %}warning{% else %}primary{% endif %}" style="margin-bottom: 5px">Title</a>#}
{#</a>#}
{#          </li>#}
{##}
{#          <li class="nav-item">#}
{#            <a class="nav-link" name="price" href="{% url 'core:home' %}">Discount</a>#}
{#              <a name="price" href="?price=True" class="btn btn-{% if 'discount_price' in request.GET %}warning{% else %}primary{% endif %}" style="margin-bottom: 5px">Price</a>#}
{#          </li>#}

{#          <li class="nav-item">#}
{#            <a class="nav-link" name="cater" href="#">Catering</a>#}
{#              <a href="?discount_price=True" class="btn btn-{% if 'discount_price' in request.GET %}warning{% else %}primary{% endif %}" style="margin-bottom: 5px">Discount Price#}
{#</a>#}
{#          </li>#}
{#             <li class="nav-item">#}
{#            <a class="nav-link" name="toilet" href="#">Portable Toilets</a>#}
{#          </li>#}
{#  </form>#}
        </ul>

      </div>
        <!-- Links -->

<form class="form-inline my-2 my-lg-1" action="#" method="get">
  <input
      class="form-control mr-sm-2"
      type="text"
      placeholder="Search"
      aria-label="Search"
      name='q'>
  <button id="search" class="btn btn-outline-success my-2 my-sm-0" type="submit" style="color: #0b51c5;width: 100px">Search</button>
</form>


{#        <form class="form-inline">#}
{#          <div class="md-form my-0">#}
{#            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">#}
{#          </div>#}
{#        </form>#}
{#     </div>#}
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

   <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn" style="background-color: white;margin-left: -280px;margin-right: -280px">

        {% for item in items %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
              {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>KSh
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
    </section>

  </div>

</main>

{% endblock content %}

static_in_env/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div>
    <style>
   #search:link {
  color: red;
}

/* visited link */
#search:visited {
  color: red;
}

/* mouse over link */
#search:hover {
  color: hotpink;
}

/* selected link */
#search:active {
  color: blue;
}
    </style>
<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
                   <a href="{% url 'core:home' %}" class="btn btn-success" style="margin-bottom: 5px">Home

              <span class="sr-only">(current)</span>
            </a>

          </li>
               <li class="nav-item active">
                   <a href="http://127.0.0.1:8000/filtering/tents" class="btn btn-success" style="margin-bottom: 5px">Tents

              <span class="sr-only">(current)</span>
            </a>

          </li>

               <li class="nav-item active">
                   <a href="http://127.0.0.1:8000/filtering/seats" class="btn btn-success" style="margin-bottom: 5px">Seats

              <span class="sr-only">(current)</span>
            </a>

          </li>
            <li class="nav-item active">
                   <a href="http://127.0.0.1:8000/filtering/Toilets" class="btn btn-success" style="margin-bottom: 5px">Toilets

              <span class="sr-only">(current)</span>
            </a>

          </li>
                 <li class="nav-item active">
                   <a href="http://127.0.0.1:8000/filtering/catering" class="btn btn-success" style="margin-bottom: 5px">Catering

              <span class="sr-only">(current)</span>
            </a>

          </li>

{##}
{#            <form action="filtering.html" method="get">#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" name="tent" href="{% url 'core:filtering' %}">Tents</a>#}
{#              <a href="?title=True" class="btn btn-{% if 'title' in request.GET %}warning{% else %}primary{% endif %}" style="margin-bottom: 5px">Title</a>#}
{#</a>#}
{#          </li>#}
{##}
{#          <li class="nav-item">#}
{#            <a class="nav-link" name="price" href="{% url 'core:home' %}">Discount</a>#}
{#              <a name="price" href="?price=True" class="btn btn-{% if 'discount_price' in request.GET %}warning{% else %}primary{% endif %}" style="margin-bottom: 5px">Price</a>#}
{#          </li>#}

{#          <li class="nav-item">#}
{#            <a class="nav-link" name="cater" href="#">Catering</a>#}
{#              <a href="?discount_price=True" class="btn btn-{% if 'discount_price' in request.GET %}warning{% else %}primary{% endif %}" style="margin-bottom: 5px">Discount Price#}
{#</a>#}
{#          </li>#}
{#             <li class="nav-item">#}
{#            <a class="nav-link" name="toilet" href="#">Portable Toilets</a>#}
{#          </li>#}
{#  </form>#}
        </ul>

      </div>
        <!-- Links -->

<form class="form-inline my-2 my-lg-1" action="#" method="get">
  <input
      class="form-control mr-sm-2"
      type="text"
      placeholder="Search"
      aria-label="Search"
      name='q'>
  <button id="search" class="btn btn-outline-success my-2 my-sm-0" type="submit" style="color: #0b51c5;width: 100px">Search</button>
</form>


{#        <form class="form-inline">#}
{#          <div class="md-form my-0">#}
{#            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">#}
{#          </div>#}
{#        </form>#}
{#     </div>#}
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn" style="background-color: white;margin-left: -280px;margin-right: -280px">

        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
              {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top" style=".card-img-top {
height: 250px !important;
}">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>KSh
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

  </div>
</main>
    </div>
{% endblock content %}

static_in_env/templates/navbar.html
{% load cart_template_tags %}


<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="/"><strong class="blue-text">ServLink</strong></a>
      <a class="navbar-brand waves-effect" href="{% url 'core:about' %}"><strong class="blue-text">About</strong></a>
    <a class="navbar-brand waves-effect" href="{% url 'admin:index' %}"><strong class="blue-text">Admin</strong></a>
 <a class="navbar-brand waves-effect" href="{% url 'core:contact' %}"><strong class="blue-text">Contact Us</strong></a>
    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        {% comment %} <li class="nav-item active">
          <a class="nav-link waves-effect" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
        </li> {% endcomment %}
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
                         <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:report' %}">
            <span class="clearfix d-none d-sm-inline-block"> Reports </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
          </a>
        </li>
        {% else %}
             <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'core:report' %}">
            <span class="clearfix d-none d-sm-inline-block"> Reports </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Login </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

static_in_env/templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">Ksh{{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-Ksh{{ order.coupon.amount }}</span>
        </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (Ksh)</span>
            <strong>Ksh{{ order.get_total }}</strong>
        </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
{#                <button class="btn btn-secondary btn-md waves-effect m-0" type="#">Redeem</button>#}
            </div>
        </div>
    </form>
    {% endif %}

</div>

static_in_env/templates/payment-confirmation.html
{ {% extends 'base.html' %}}

<h1>Payment Conf</h1>

static_in_env/templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

static_in_env/templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>